version: '3.8'

services:
    php-fpm:
        image: graffino/ninja_php:v1
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./.docker/logs/php-fpm/:/var/log/php-fpm/
            - ./dist-wp/:/var/www
        networks:
            - servers
        ports:
            - '9001:9001'
            - '9000:9000'
        depends_on: 
            - mariadb
    nginx:
        image: graffino/ninja_nginx:v1
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        volumes: 
            - ./dist-wp/:/var/www
            - ./.docker/logs/nginx/:/var/log/nginx
            - ./.docker/nginx/conf.d:/etc/nginx/templates
        networks:
            - servers
        ports:
            - '8080:80'
        depends_on: 
            - php-fpm
    mariadb:
        image: graffino/ninja_mariadb:v1
        build:
            context: .
            dockerfile: .docker/mariadb/Dockerfile
        volumes: 
            - ./.docker/logs/mariadb:/var/log/mysql
            - mariadb:/var/lib/mysql
        networks:
            - servers
        ports:
            - '8306:3306'
configs:
    env_config:
        file: ./.env

networks:
    servers:
        driver: bridge

volumes:
    mariadb: